-- MySQL Script generated by MySQL Workbench
-- 06/19/15 11:06:29
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema source_medical_dummy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `source_medical_dummy` ;
CREATE SCHEMA IF NOT EXISTS `source_medical_dummy` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `source_medical_dummy` ;

-- -----------------------------------------------------
-- Table `source_medical_dummy`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `source_medical_dummy`.`patient` ;

CREATE TABLE IF NOT EXISTS `source_medical_dummy`.`patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `surname` VARCHAR(200) NULL,
  `birthdate` DATE NOT NULL,
  `address` VARCHAR(250) NULL,
  `identifier` VARCHAR(250) NOT NULL,
  UNIQUE INDEX `identifier_UNIQUE` (`identifier` ASC),
  PRIMARY KEY (`patient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `source_medical_dummy`.`drug`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `source_medical_dummy`.`drug` ;

CREATE TABLE IF NOT EXISTS `source_medical_dummy`.`drug` (
  `drug_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`drug_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `source_medical_dummy`.`drug_dispensation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `source_medical_dummy`.`drug_dispensation` ;

CREATE TABLE IF NOT EXISTS `source_medical_dummy`.`drug_dispensation` (
  `drug_dispensation_id` INT NOT NULL AUTO_INCREMENT,
  `drug_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `date_dispensation` DATETIME NULL,
  PRIMARY KEY (`drug_dispensation_id`),
  INDEX `patient_fk` (`patient_id` ASC),
  INDEX `drug_fk` (`drug_id` ASC),
  CONSTRAINT `pat_drg_disp_fk`
    FOREIGN KEY (`patient_id`)
    REFERENCES `source_medical_dummy`.`patient` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `drg_drg_disp_fk`
    FOREIGN KEY (`drug_id`)
    REFERENCES `source_medical_dummy`.`drug` (`drug_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `source_medical_dummy`.`patient`
-- -----------------------------------------------------
START TRANSACTION;
USE `source_medical_dummy`;
INSERT INTO `source_medical_dummy`.`patient` (`patient_id`, `name`, `surname`, `birthdate`, `address`, `identifier`) VALUES (1, 'Bruce', 'Wayne', '1984-02-12', 'Gotham City, 100', '0000001A');
INSERT INTO `source_medical_dummy`.`patient` (`patient_id`, `name`, `surname`, `birthdate`, `address`, `identifier`) VALUES (2, 'Jack', 'Sparrow', '1975-05-10', 'Caribbean Village, 200', '0000001B');
INSERT INTO `source_medical_dummy`.`patient` (`patient_id`, `name`, `surname`, `birthdate`, `address`, `identifier`) VALUES (3, 'Freddy', 'krueger', '2000-01-02', 'Helm Street, 400', '0000001C');

COMMIT;


-- -----------------------------------------------------
-- Data for table `source_medical_dummy`.`drug`
-- -----------------------------------------------------
START TRANSACTION;
USE `source_medical_dummy`;
INSERT INTO `source_medical_dummy`.`drug` (`drug_id`, `name`) VALUES (1, 'Paracetamol');
INSERT INTO `source_medical_dummy`.`drug` (`drug_id`, `name`) VALUES (2, 'Aspirin');
INSERT INTO `source_medical_dummy`.`drug` (`drug_id`, `name`) VALUES (3, 'INH');

COMMIT;


-- -----------------------------------------------------
-- Data for table `source_medical_dummy`.`drug_dispensation`
-- -----------------------------------------------------
START TRANSACTION;
USE `source_medical_dummy`;
INSERT INTO `source_medical_dummy`.`drug_dispensation` (`drug_dispensation_id`, `drug_id`, `patient_id`, `quantity`, `date_dispensation`) VALUES (1, 1, 1, 10, '2015-01-01');
INSERT INTO `source_medical_dummy`.`drug_dispensation` (`drug_dispensation_id`, `drug_id`, `patient_id`, `quantity`, `date_dispensation`) VALUES (2, 2, 2, 5, '2015-01-01');
INSERT INTO `source_medical_dummy`.`drug_dispensation` (`drug_dispensation_id`, `drug_id`, `patient_id`, `quantity`, `date_dispensation`) VALUES (3, 3, 3, 15, '2015-01-01');

COMMIT;

